### PR TITLE
#162948880  Liking and disliking Articles

### PR DESCRIPTION
**Pull request by danuluma**
#### What does this PR do?
Adds ability for users to like or dislike articles

#### Description of Task(s) to be completed?
* Implements liking and disliking feature on the frontend

#### How should this be manually tested?
* Pull the branch `git fetch origin ft-liking-162948880:ft-liking-162948880`
* Checkout to the branch `git checkout ft-liking-162948880`
* Install dependencies `npm install`
* Run the server `npm start`

* Alternatively, simply click on this [link](https://ah-alpha-frontend-stagin-pr-28.herokuapp.com/) to view the deployed version

### Screenshots
image

#### What are the relevant pivotal tracker stories?
[#162948880](https://www.pivotaltracker.com/story/show/162948880)

### CODE REVIEW

**Review by boltonotieno — APPROVED** [review]
Tested functionality and it's working fine.

**Review by Deekerubo — APPROVED** [review]

**Review by Ruiru11 — COMMENTED** [review]
the title is off kindly fix that to articles

**Review by Ruiru11 — APPROVED** [review]
Good work i have tested the feature and it works

**Review by boltonotieno — CHANGES_REQUESTED** [review]
Kindly squash your commits to one

**Review by boltonotieno — APPROVED** [review]
Functionality working as expected

**Pull request merged**
